accounts/urls.py
from django.urls import path
from accounts.views import RegisterView, ProfileView

app_name = 'accounts'

urlpatterns = [
    path("<str:username>/profile/", ProfileView.as_view(), name='profile'),
    path("register/", RegisterView.as_view(), name='register'),
]

blog/urls.py
from django.urls import path
from blog.views import BlogListView, BlogCreateView, BlogDetailView, BlogUpdateView, UserBlogListView, BlogDeleteView

app_name = 'blog'

urlpatterns = [
    path("", BlogListView.as_view(), name='home'),
    path("<str:username>/blogs/", UserBlogListView.as_view(), name='usersallblog'),
    path("<str:username>/<slug:slug>/view/", BlogDetailView.as_view(), name='detail'),
    path("<str:username>/<slug:slug>/delete/", BlogDeleteView.as_view(), name='delete'),
    path("<str:username>/<slug:slug>/edit/", BlogUpdateView.as_view(), name='update'),
    path("create/", BlogCreateView.as_view(), name='create'),
]

blogwebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include('django.contrib.auth.urls')),
    path("accounts/", include('accounts.urls')),
    path("", include('blog.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import (AbstractUser,
                                        UserManager as AbstractUserManager)

# Create your models here.

class UserManager(AbstractUserManager):
    pass

class User(AbstractUser):
    objects = UserManager()

    def __str__(self):
        return str(self.username)

blog/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify
from django.urls import reverse_lazy

# Create your models here.

class Blog(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    author = models.ForeignKey(
                settings.AUTH_USER_MODEL,
                on_delete=models.CASCADE,
                )
    slug = models.SlugField(max_length=49, unique=True)
    publish_datetimestamp = models.DateTimeField(auto_now_add=True)
    edited_datetimestamp = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse_lazy('blog:detail', kwargs={'username': self.author.username,
                                            'slug': self.slug})

    def __str__(self):
        return str(self.title)

    def save(self, *args, **kwargs):
        slug = slugify(self.title[:50])
        count = self.__class__.objects.filter(
                author=self.author,
                slug__startswith=slug).count()
        self.slug = slug

        if count > 0:
            self.slug = slug + str(count)

        super().save(*args, **kwargs)

accounts/forms.py
from django.contrib.auth.forms import (UserCreationForm,
                                       UserChangeForm)
from accounts.models import User


class UserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = User


class UserChangeForm(UserChangeForm):

    class Meta(UserChangeForm.Meta):
        model = User

accounts/views.py
from django.shortcuts import render
from django.views.generic import CreateView, DetailView
from accounts.forms import UserCreationForm
from accounts.models import User
from django.urls import reverse_lazy

# Create your views here.

class RegisterView(CreateView):
    form_class = UserCreationForm
    model = User
    template_name = 'accounts/register.html'
    success_url = reverse_lazy('blog:home')

class ProfileView(DetailView):
    template_name = 'accounts/profile.html'
    model = User
    slug_field = 'username'
    slug_url_kwarg = 'username'
    context_object_name = "user_object"

blog/views.py
from django.contrib.auth.mixins import (LoginRequiredMixin,
                                        UserPassesTestMixin)
from django.shortcuts import render
from django.views.generic import (ListView,
                                  CreateView,
                                  DetailView,
                                  DeleteView,
                                  TemplateView)
from django.views.generic.edit import UpdateView
from blog.models import Blog
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect

# Create your views here.


class BlogListView(ListView):
    template_name = 'blog/home.html'
    model = Blog
    context_object_name = 'blog_list'

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.order_by('-publish_datetimestamp')
    

class UserBlogListView(ListView):
    template_name = 'blog/user_blogs.html'
    model = Blog
    context_object_name = 'blog_list'

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(author=self.request.user.id).order_by('-publish_datetimestamp')
    

class BlogDetailView(DetailView):
    template_name = 'blog/detail.html'
    model = Blog
    context_object_name = 'blog'
    slug_field = 'slug'

class BlogUpdateView(UserPassesTestMixin, UpdateView):
    model = Blog
    template_name = 'blog/edit.html'
    fields = ['title', 'content']
    permission_denied_message = 'hahahhaahah'

    def test_func(self):
        obj = self.get_object()
        return obj.author == self.request.user

class BlogCreateView(LoginRequiredMixin, CreateView):
    template_name = 'blog/create.html'
    model = Blog
    fields = ['title', 'content']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class BlogDeleteView(UserPassesTestMixin, DeleteView):
    template_name = 'blog/delete.html'
    model = Blog

    def test_func(self):
        print(self.request)
        return self.get_object().author == self.request.user

    def form_valid(self, form):
        success_url = reverse_lazy('blog:usersallblog', kwargs={"username": self.request.user.username})
        self.object.delete()
        return HttpResponseRedirect(success_url)

templates/accounts/profile.html
{% extends 'base.html' %}
{% block title %} User Profile {% endblock title %}
{% block body %}
{{user_object.username}}
{% endblock body %}

templates/accounts/register.html
{% extends 'base.html' %}
{% block title %} User Registration {% endblock title %}
{% block body %}
<div class="d-flex flex-column">
    <form action="" method='POST' class="form-control w-50 mx-auto mt-5">
        {% csrf_token %}
        <h1>Register</h1>
        {{form.as_p}}
        <input type="submit" value='Register' class="btn bg-success text-light">
    </form>
</div>
{% endblock body %}

templates/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>{% block title %} {% endblock title %}</title>
</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'blog:home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Link</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            {{user.username}}
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="{% url 'blog:create' %}">Create Blog</a></li>
                            <li><a class="dropdown-item" href="{% url 'blog:usersallblog' user.username %}">Your
                                    Blogs</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
                        </ul>
                        {% else %}
                    <li class="nav-item dropdown">
                        <a class="nav-link text-success" href="{% url 'login' %}">Login/Register</a>
                    </li>
                    {% endif %}
                    </li>
                    <!-- <li class="nav-item">
                        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                    </li> -->
                </ul>
                <form class="d-flex">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
    {% block body %} {% endblock body %}
</body>

</html>

templates/blog/create.html
{% extends 'base.html' %}
{% block title %} {% endblock title %}
{% block body %}
<h1>Create Blog</h1>
<form action="" method='POST'>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value='publish'>
</form>
{% endblock body %}

templates/blog/delete.html
{% extends 'base.html' %}
{% block title %} Delete {% endblock title %}
{% block body %}
<form action='' method='POST' class="form-control">
    {% csrf_token %}
    <h1>Confirmation</h1>
    <div class="container-flow">
        <h3 class="text-danger">Are you sure you want to delete your post</h3>
        <h3>{{object.title}}</h3>
        <p>{{object.content|slice:":200"}}</p>
    </div>
    {{form.as_p}}
    <input type="submit" class="btn btn-danger" value="delete" />
</form>
{% endblock body %}

templates/blog/detail.html
{% extends 'base.html' %}
{% block title %} Blog | Detail {% endblock title %}
{% block body %}
<div class="container-fluid px-3 py-4">
    <h1>{{blog.title}}</h1>
    <p class="px-2">{{blog.content}}</p>
    <div class="w-100 d-flex justify-content-between">
        <div></div>
        <div>
            <h5>Published: {{blog.publish_datetimestamp}}</h5>
            <h5>Edited: {{blog.edited_datetimestamp}}</h5>
            <h5 class="">By: <a href="{% url 'accounts:profile' object.author %}">{{blog.author.username}}</a></h5>
            
        </div>
    </div>
</div>
{% endblock %}

templates/blog/edit.html
{% extends 'base.html' %}
{% block title %} Blog | Edit {% endblock title %}
{% block body %}
<h1>Edit</h1>
<form action="" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="edit">
</form>
{% endblock body %}

templates/blog/home.html
{% extends 'base.html' %}
{% block title %} Blog | Home {% endblock title %}
{% block body %}
{% if object_list %}
<div class="list-group container-fluid">
  <h1 class="mx-3 my-2">Latest Blogs</h1>
  <div class="mx-4 w-50">
    {% for object in object_list %}
    <div href="{% url 'blog:detail' object.author.username object.slug %}" class="list-group-item list-group-item-action mb-2" aria-current="true">
      <div class="d-flex w-100 justify-content-between">
        <h5 class="mb-1">{{object.title}}</h5>
        <small></small>
      </div>
      <p class="mb-1 ms-1">{{object.content|slice:":200"}}<a href="{% url 'blog:detail' object.author.username object.slug %}" class="link-info">...Read More</a></p>
      <div class="d-flex w-100 justify-content-between">
      <span>Author: <a href="{% url 'accounts:profile' object.author %}">{{object.author.username}}</a></span>
      <small>{{object.publish_datetimestamp|timesince}} ago</small>
      </div>
    </div>
    {% endfor %}
  </div>
  <!-- <a href="" class="list-group-item list-group-item-action">
    <div class="d-flex w-100 justify-content-between">
      <h5 class="mb-1">List group item heading</h5>
      <small class="text-muted">3 days ago</small>
    </div>
    <p class="mb-1">Some placeholder content in a paragraph.</p>
    <small class="text-muted">And some muted small print.</small>
  </a>
  <a href="" class="list-group-item list-group-item-action">
    <div class="d-flex w-100 justify-content-between">
      <h5 class="mb-1">List group item heading</h5>
      <small class="text-muted">3 days ago</small>
    </div>
    <p class="mb-1">Some placeholder content in a paragraph.</p>
    <small class="text-muted">And some muted small print.</small>
  </a> -->
</div>
{% endif %}
{% endblock body %}

templates/blog/user_blogs.html
{% extends 'base.html' %}
{% block title %} Blog | Home {% endblock title %}
{% block body %}
{% if object_list %}
<div class="list-group container-fluid">
    <h1 class="mx-3 my-2">Your Blogs</h1>
    <div class="mx-4 w-50">
        {% for object in object_list %}
        <div
            class="list-group-item list-group-item-action mb-2" aria-current="true">
            <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1">{{object.title}}</h5>
                <small></small>
            </div>
            <p class="mb-1 ms-1">{{object.content|slice:":200"}}<span class="text-info"><a href="{% url 'blog:detail' object.author.username object.slug %}">...Read More</a></span></p>
            <div class="d-flex w-100 justify-content-between">
                <a href="{% url 'blog:delete' user.username object.slug %}" class="link-danger">Delete Post</a>
                <a href="{% url 'blog:update' user.username object.slug %}" class="link-success me-auto ms-2">Edit Post</a>
                <small>{{object.publish_datetimestamp|timesince}} ago</small>
            </div>
        </div>
        {% endfor %}
    </div>
    <!-- <a href="" class="list-group-item list-group-item-action">
    <div class="d-flex w-100 justify-content-between">
      <h5 class="mb-1">List group item heading</h5>
      <small class="text-muted">3 days ago</small>
    </div>
    <p class="mb-1">Some placeholder content in a paragraph.</p>
    <small class="text-muted">And some muted small print.</small>
  </a>
  <a href="" class="list-group-item list-group-item-action">
    <div class="d-flex w-100 justify-content-between">
      <h5 class="mb-1">List group item heading</h5>
      <small class="text-muted">3 days ago</small>
    </div>
    <p class="mb-1">Some placeholder content in a paragraph.</p>
    <small class="text-muted">And some muted small print.</small>
  </a> -->
</div>
{% endif %}
{% endblock body %}